### ISSUE TITLE
Investigate Minio integration within Pachyderm setup

### ISSUE THREAD

**Issue by carmat88** [pharmbio/cpsign-service-management#15]
Pachyderm needs an object store and a k8s PV for etcd in order to be a working distributed cluster. One of the most recommend object store alternative for pachyderm seems to be [Minio](https://minio.io/).

Also mentioned in Pachyderm's documentation:
- https://docs.pachyderm.io/en/latest/deployment/on_premises.html?highlight=minio

**Comment by Snapple49** [comment]
Done!

Installed with Minio helm chart, running with NAS-gateway and pachyderm uses s3 fields to connect.
