### ISSUE TITLE
Update docker hub credentials in Travis

### ISSUE THREAD

**Issue by carmat88** [pharmbio/cpsign-service-management#23]
Soon my docker hub credentials will not be used longer for this repo CI. Thus they would need to be replaced with someone's else or maybe to create a travis account for Docker hub (only if it made sense though).

**Comment by carmat88** [comment]
Hej @Snapple49 ! Please whenever we have time, let's make sure to update the docker hub credentials in Travis. Cheers!

**Comment by Snapple49** [comment]
Credentials are now on my account!
