### ISSUE TITLE
make release for parallel logd

### ISSUE THREAD

**Issue by Snapple49** [pharmbio/cpsign-service-management#25]
We should make a release so we have a stable version now that the LogD workflow seems finished. We should then also set up tags for docker to be based on releases

- [x] Verify LogD works after latest build
- [x] Run LogD with full query and parallellisation

**Comment by carmat88** [comment]
Hej @Snapple49 ! As per our last testing (beside the infrastructure limitations to be discussed with the other folks), we should be all good with the above steps.

Let me know what you think. Cheers!

**Comment by Snapple49** [comment]
I did a release now!
